### ISSUE TITLE
Labyrinths not showing - new installation

### ISSUE THREAD

**Issue by Thoughtfulmonkey** [olab/Open-Labyrinth#100]
I have newly installed openlabyrinth on a server, and when I click on the play button to see a labyrinth I get the 404 page instead.

I've tried narrowing down the error but I've reached a dead end.

It seems to be failing in 
    application/classes/model/leap/user/session.php
    in the createSession function 
    on $builder->execute();

Everything is fine locally, it's just on the server.  I can't even turn on the error reporting, so it could well be a server setting, but any clues would be welcome.  It's HTTPS.

**Comment by Thoughtfulmonkey** [comment]
It turned out to be another issue with an sql_mode setting, this time STRICT_TRANS_TABLE.

The query executed to create the session passed a NULL value for the notCummulative field in the user_sessions table.

I've just turned all the sql_mode settings off for now, but the database structure for user_sessions.notCumulative is set not to be NULL, with no default value, so passing in NULL would seem to be a bug.

**Comment by sergey-rud** [comment]
Thank you again, @Thoughtfulmonkey 

Please see solution here #99
