### ISSUE TITLE
Install Openlabyrinth

### ISSUE THREAD

**Issue by yzidoun** [olab/Open-Labyrinth#101]
Hi ,

I have some issues with openlabyrinth install, i have all the preset up but i'm stuck with this error :
 Table 'openlabyrinth.dforum' doesn't exist

**Comment by topps** [comment]
It sounds like the install process was interrupted part way through. That table is created in MySQL as part of the standard install. So either the MySQL database part was not completed for some reason, or sometimes this arises because the software does not have the correct access permissions to the usual folders in the machine’s directory structure.

Does that help? Please email me direct to continue the conversation.

dt

From: yzidoun
Reply-To: olab/Open-Labyrinth
Date: Friday, February 5, 2016 at 2:16 PM
To: olab/Open-Labyrinth
Subject: [Open-Labyrinth] Install Openlabyrinth (#101)


Hi ,

I have some issues with openlabyrinth install, i have all the preset up but i'm stuck with this error :
Table 'openlabyrinthdforum' doesn't exist

**Comment by yzidoun** [comment]
Can i have your email please ?

**Comment by cyles** [comment]
It could be a timeout issue.  OLab recommends 300 seconds, which I have found to be necessary.  The default of 30 is not long enough except on very fast servers.

Cyle

-----------------------------
Cyle Sprick PhD | Director Sim Unit | School of Medicine - Flinders University | cyle.sprick@flinders.edu.au<mailto:cyle.sprick@flinders.edu.au> | 0402 477 296 | +61 8 7221 8860

**Comment by yzidoun** [comment]
yes i set the maximum execution to 300 but still stuck with this error

**Comment by yzidoun** [comment]
Hi Mr Topps,

Can you help me with the Install problem ?

2016-02-08 15:11 GMT+00:00 cyles <notifications@github.com>:

> It could be a timeout issue. OLab recommends 300 seconds, which I have
> found to be necessary. The default of 30 is not long enough except on very
> fast servers.
>
> Cyle
>
> -----------------------------
> Cyle Sprick PhD | Director Sim Unit | School of Medicine - Flinders
> University | cyle.sprick@flinders.edu.au<mailto:
> cyle.sprick@flinders.edu.au> | 0402 477 296 | +61 8 7221 8860
>
> From: David Topps [mailto:notifications@github.com]
> Sent: Monday, 8 February 2016 9:21 AM
> To: olab/Open-Labyrinth <Open-Labyrinth@noreply.github.com>
> Subject: Re: [Open-Labyrinth] Install Openlabyrinth (#101)
>
> It sounds like the install process was interrupted part way through. That
> table is created in MySQL as part of the standard install. So either the
> MySQL database part was not completed for some reason, or sometimes this
> arises because the software does not have the correct access permissions to
> the usual folders in the machine’s directory structure.
>
> Does that help? Please email me direct to continue the conversation.
>
> dt
>
> From: yzidoun
> Reply-To: olab/Open-Labyrinth
> Date: Friday, February 5, 2016 at 2:16 PM
> To: olab/Open-Labyrinth
> Subject: [Open-Labyrinth] Install Openlabyrinth (#101)
>
>
> Hi ,
>
> I have some issues with openlabyrinth install, i have all the preset up
> but i'm stuck with this error :
> Table 'openlabyrinthdforum' doesn't exist
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/olab/Open-Labyrinth/issues/101>.
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/olab/Open-Labyrinth/issues/101#issuecomment-181137226>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olab/Open-Labyrinth/issues/101#issuecomment-181406987>
> .
>



-- 
*ZIDOUN Youness*
*Doctorant en informatique*
*Laboratoire de Traitement de l'Information*

*Faculté des sciences Ben M'sik - Casablanca *

**Comment by mattsimpson** [comment]
Hello yzidoun,

Would you be able to post the exact error you're receiving during installation. I've tried to find "openlabyrinthdforum" referenced, and have not been able to locate anything. It may help if I have the error in it's entirety.

Thanks,
Matt

**Comment by topps** [comment]
Sorry, part of the difficulty here is because we are both communicating through the listserv.

Please email me direct via info@openlabyrinth.ca and then I will also have your email.

I’m not trying to exclude the others on the listserv from this. Thanks to Cyle and Matt for suggestions.

I think you will need to reinstall from scratch. The table ‘dforum’ is one of the tables that is created during the install process. Cyle’s suggestion is a good one. Your database may have timed out during the install and not all the needed tables created. It is unlikely that just one table is affected. This will just be the one that shows up first. Are you able to change the database default timeout settings on your server?

dt

**Comment by yzidoun** [comment]
hi mattsimpson,
The exact error is this : 
Table 'openlabyrinth.dforum' doesn't exist

Here is my log apache error : 
[Mon Feb 15 16:08:28.305086 2016] [:error] [pid 3180:tid 768] [client 127.0.0.1:50342] PHP Warning:  mysql_query(): MySQL server has gone away in C:\\Program Files (x86)\\EasyPHP-DevServer-14.1VC11\\data\\localweb\\Openlab\\installation\\classes\\installation.php on line 802, referer: http://127.0.0.1/
[Mon Feb 15 16:08:28.321087 2016] [:error] [pid 3180:tid 768] [client 127.0.0.1:50342] PHP Warning:  mysql_query(): Error reading result set's header in C:\\Program Files (x86)\\EasyPHP-DevServer-14.1VC11\\data\\localweb\\Openlab\\installation\\classes\\installation.php on line 802, referer: http://127.0.0.1/

**Comment by topps** [comment]
I would agree with Cyle’s assessment. To me, it looks like your MySQL server timed out during one of the longer queries. Can you set the timeout to 300 seconds rather than the default 30 seconds?

dt

**Comment by yzidoun** [comment]
Hello everybody,
So i'm trying to reinstall from scratch, i get this list of errors this time : 

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 605

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758
Duplicate entry '7' for key 'PRIMARY'

**Comment by mattsimpson** [comment]
What version of PHP are you using yzidoun?

**Comment by yzidoun** [comment]
Hi Matt,
I'm on PHP 5.5.8.

**Comment by larjohn** [comment]
These are two distinct issues. 
For the warnings, we need to update the code to be in par with the new versions of php. A temporary measure is to disable error logging. I can't recall if you can disable this specific error logging, but I am afraid you might have to sacrifice any error logging altogether.

Second, the real error is that primary key guy in the last line. I am mobile right now so I cannot have a good look at the line. Maybe you should first delete remaining tables before reattempting to instal OpenLabyrinth.

**Comment by topps** [comment]
That might be a contributing factor. When we (and most sites) were on PHP 5.3, we were not having such issues. Since the default PHP installation has variably moved to 5.4, 5.5 or later, we are seeing more of these kinds of issues.

ITRex is aware of this but we have not allocated a block of time to resolving this yet. I guess that this also in some ways ties in to the general issue that we have been discussing re modules, versions of OLab etc and making the installation more modular.

One thing that might help us in deciding where to go with this (speaking as a non-expert, and maybe this is irrelevant) - PHP seemed to standardize on 5.3 for quite some time and now there has been a jump in sub-releases. Is there a new generally popular version that we should aim to standardize on? Or are there better ways to proof us against such a dependency?

From: yzidoun
Reply-To: olab/Open-Labyrinth
Date: Thursday, February 18, 2016 at 10:12 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Install Openlabyrinth (#101)


Hi Matt,
I'm on PHP 5.5.8.

**Comment by topps** [comment]
Thanks, Matt and Larjohn, for your suggestions. One other thing that occurs to me, based on previous installation failures that I have had: did you remove everything before trying again?

While it is fairly easy to remove the application’s code, it is a bit more of a nuisance to remove the openlabyrinth database from MySQL, or to reinstall MySQL and PHP when needed.

I have not had to do a reinstall on Windows. When I installed on WAMP, it just worked. So my suggestions may not be accurate or helpful. dt

From: yzidoun
Reply-To: olab/Open-Labyrinth
Date: Thursday, February 18, 2016 at 9:59 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Install Openlabyrinth (#101)


Hello everybody,
So i'm trying to reinstall from scratch, i get this list of errors this time :

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 605

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758

Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Openlab\installation\classes\installation.php on line 758
Duplicate entry '7' for key 'PRIMARY'

**Comment by a-zharkov** [comment]
@yzidoun Hi. What branch of OLab did you use ?

**Comment by yzidoun** [comment]
@a-zharkov Hi, The last one.

**Comment by a-zharkov** [comment]
@yzidoun I mean - master, develop, release-candidate ?

**Comment by yzidoun** [comment]
@a-zharkov  master

**Comment by a-zharkov** [comment]
@topps it looks like we need to create a new release, because in release-candidate branch all these issues fixed.

**Comment by yzidoun** [comment]
@a-zharkov it's a little bit urgent for me to install Olab. i'm working with EasyPHP for production, can you send me a stable version or guide me through your way to install it.

**Comment by a-zharkov** [comment]
@yzidoun if you are using Git to get the code, then do the following:

1) git clone https://github.com/olab/Open-Labyrinth.git
2) cd Open-Labyrinth
3) git checkout release-candidate

If you downloaded the archive, then download it here:
https://github.com/olab/Open-Labyrinth/archive/release-candidate.zip

**Comment by topps** [comment]
I wonder if EasyPHP might be one issue. Have not used this. I don’t know how much variation there is between PHP flavours and environments. While these things are all supposed to be interoperable, we know this not to be true.

From: yzidoun
Reply-To: olab/Open-Labyrinth
Date: Monday, February 22, 2016 at 6:54 AM
To: olab/Open-Labyrinth
Cc: David Topps
Subject: Re: [Open-Labyrinth] Install Openlabyrinth (#101)


@a-zharkov<https://github.com/a-zharkov> it's a little bit urgent for me to install Olab. i'm working with EasyPHP for production, can you send me a stable version or guide me through your way to install it.

**Comment by topps** [comment]
Yup, that would normally be the best choice. You will probably be better off using the release-candidate branch. It has better fixes for PHP version. Remember to clear out all the detritus from your last install. dt

**Comment by yzidoun** [comment]
Hi @topps  @a-zharkov  @mattsimpson  @larjohn  @cyles ,

Thanks a lot for all your help, the release-candidate is great. I had some problems but not that much so it worked finally and i can enjoy Olab.

Again, thank you all.

PS: @topps your tutos on youtube helped me a lot starting openlabyrinth thank you .
