### ISSUE TITLE
Rule does not work

### ISSUE THREAD

**Issue by Pedklin** [olab/Open-Labyrinth#106]
Hi!
We have installed OpenLabyrinth server: http://olab.pedklin.ru/
I added the global Rule:
IF Biohim_select > 0 THEN GOTO [[INFO:68]], Biohim_select = 0
But GOTO in this rule never fullfils. Biohim_select = 0 works good.
Would you advise us any reasons?
Thanks

**Comment by a-zharkov** [comment]
Hi @Pedklin .
Rule should be:
IF Biohim_select > 0 THEN GOTO **[[NODE:68]]**, Biohim_select = 0

**Comment by topps** [comment]
Another small tip: I also follow such commands with BREAK

IF Biohim_select > 0 THEN GOTO [[NODE:68]], Biohim_select = 0, BREAK;

One other small tip: For both Node names and Counter names, the parser sometimes has problems if the name contains another valid name that is shorter. Reference numbers work regardless.

**Comment by Pedklin** [comment]
Thank you!
It's ok now)
