### ISSUE TITLE
Error migrating openlabyrinth

### ISSUE THREAD

**Issue by Catskan** [olab/Open-Labyrinth#108]
Hi,

I want to migrate my existing OpenLabyrinth installation but I a error message

>  Whoops! Looks like something got lost in the Labyrinth.

Database is imported in my new DB server and the openlabyrinth folder in the new /var/www/html

My error is a wrong mysql authentification, but, what is the file that I need to change this informations ?

Thanks you in advance

**Comment by sergey-rud** [comment]
Hi!
Database credentials should be set in the www/application/config/database.php

Note: press cmd+q to see error details.

**Comment by Catskan** [comment]
Thanks, it's good !
