### ISSUE TITLE
Error access new install 

### ISSUE THREAD

**Issue by Catskan** [olab/Open-Labyrinth#109]
Hi,

I made a new and clean install of OpenLabyrinth from git repository. After the installation, I see a blank page.

tail -f /var/log/apache2/error.log tell me :
`[Tue Jun 21 14:18:51.792419 2016] [:error] [pid 9542] [client 134.59.53.4:1415] PHP Fatal error:  Call to a member function uri() on null in /var/www/html/openlabyrinth/application/classes/kohana/exception.php on line 50
`

What is this error ?

Thanks you in advance

**Comment by sergey-rud** [comment]
Hi @Catskan 
Could you please provide more details about your server software:
PHP version - ?
MySQL version - ?
Which OpenLabyrinth branch you are use? (master, release-candidate, specific release...)

Where did you get an error (blank page)? On the home page?
Could you please check /path_to_openlabyrinth/www/application/logs directory and provide error messages if this directory isn't empty.

Thank you.

**Comment by Catskan** [comment]
Hi,

Oh sorry ! 
PHP Version : 5.6.22
MySQL Version : MariaDB 10.1

I use `git clone  https://github.com/olab/Open-Labyrinth.git` (selected release-candidate).

I have a blank page on the homepage (index.php) and I have not error message.

In my path www/application/log, I have "empty.folder" only.

**Comment by sergey-rud** [comment]
I added few fixes to the release-candidate.
Please try to do a fresh install but note that release-candidate requires:

1) Composer (https://getcomposer.org). When composer installed, run `composer install` on the root directory of the project.
2) Run `php vendor/bin/phinx migrate` on the same directory.

Please let me know if the problem persists.

**Comment by Catskan** [comment]
I tryed with the new version and I've same error.

When I start `composer install` on openlabyrinth directory, I have " Composer could not find a composer.json file".

**Comment by sergey-rud** [comment]
But it exists: https://github.com/olab/Open-Labyrinth/blob/release-candidate/composer.json and works, I just checked this.

Does it exist in the your project root folder?

**Comment by Catskan** [comment]
Oh, in my project folder, composer.json doesn't exist. 

git clone doesn't clone release-candidate branch ?

**Comment by sergey-rud** [comment]
It clones all branches, but default branch is master that works well, but may doesn't contain latest features and fixes, because they can be under development.

After `git clone` you should switch to release-candidate manually, if you need it.

Anyway master branch works well, so switch to the release-candidate unlikely solve your issue.

Before trying new installation (no matter release-candidate or master), make sure that your php.ini directives set as follow:
display_errors = On
error_reporting = E_ALL

(don’t forget restart apache)

That allows you to see errors on the browser, probably some of it happen during installation.

**Comment by Catskan** [comment]
I swited display_errors = On and I try a new install.

During this installation, no error message appear, but after redirection, I have same error on the index.php (with display_errors enable).

` Fatal error: Call to a member function uri() on null in /var/www/html/openlabyrinth/www/application/classes/kohana/exception.php on line 50`

**Comment by sergey-rud** [comment]
We need see stacktrace to know what causes exception. You may temporarily replace https://github.com/olab/Open-Labyrinth/blob/master/www/application/classes/kohana/exception.php#L50 this line by `'http://your_domain/'` (with quotes) to see exception details on the home page.

**Comment by Catskan** [comment]
Hi,

I modify Line 50 by : 
`'http://timide.unice.fr/openlabyrinth/www/'(Request::initial()->uri(), true)` and I have error message : > Parse error: syntax error, unexpected '(' in /var/www/html/openlabyrinth/www/application/classes/kohana/exception.php on line 50`

And when I modify line 50 by : 
`URL::'http://timide.unice.fr/openlabyrinth/www/'(Request::initial()->uri(), true)` and I have : 
> Parse error: syntax error, unexpected ''http://timide.unice.fr/openla' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/openlabyrinth/www/application/classes/kohana/exception.php on line 50 

I think I have not correcty modify this line ...

**Comment by topps** [comment]
Hi Catskan

I think that Sergey is away on holiday this week. Perhaps someone else on the listserv will be able to offer advice while he is away.

David Topps

**Comment by Catskan** [comment]
Ok I understood and I modify the line by my domain and now, I have `Kohana_Exception [ 0 ]: The requested route does not exist: error ~ SYSPATH/classes/kohana/route.php [ 106 ]` on the index page.

**Comment by sergey-rud** [comment]
Ah, I expected more specific error. Some thoughts:
* Make sure you have Apache mod_rewrite module enabled.
* Unlikely this is a reason, but you may try to change recursively permissions to 0777 (if they aren't) for the whole project to be sure that file system permissions aren’t a reason of a failure.
* Also perhaps this may help: https://github.com/olab/Open-Labyrinth/wiki/After-installation-I-try-to-login-but-I-get-404-error

**Comment by madcat2000** [comment]
Hi,
Just like above, I did a fresh install on a server with a working installation of v3.3.1 already present.
But the new installation (I tried 3.3.2 and 3.4) produced the following message after installation and going to the homepage.
`Fatal error: Call to a member function uri() on null in /data/opt/lampp/htdocs/olabdev/application/classes/kohana/exception.php on line 50`

Any ideas how to solve this? What update in 3.3.2 could be the cause of this?

(server details: PPH 5.6.3 / MySQL 5.0.11),

**Comment by Catskan** [comment]
Hi,

I came back from holidays.

- a2enmod rewrite already enabled

- chmod -R 777 : always the same message.

- create a default.conf with the exemple, and always the same message ...

**Comment by topps** [comment]
Catskan,

Can you email me direct re this, at topps@ucalgary.ca? I think I only have received messages via the Github message board. Then I may be able to connect you more effectively with the dev team.

David Topps
OpenLabyrinth Development Consortium Lead

From: Catskan
Reply-To: olab/Open-Labyrinth
Date: Monday, August 22, 2016 at 7:37 AM
To: olab/Open-Labyrinth
Cc: David Topps, Comment
Subject: Re: [olab/Open-Labyrinth] Error access new install (#109)


Hi,

I came back from holidays.

  *   a2enmod rewrite already enabled

  *   chmod -R 777 : always the same message.

  *   create a default.conf with the exemple, and always the same message ...

**Comment by sergey-rud** [comment]
Hi @Catskan

I think we will figure out it faster if you are able to provide SSH access to your server and Database credentials. You may email me sergey.rud@itrexgroup.com and I will try to install oLab on your server. Then I’ll come back here with the reason of installation failure, which may be helpful for others.

If you don’t able to do that, please clean Database, Apache and PHP log, then reinstall oLab (**master branch**) and send me DB, Apache and PHP log files (both access log and error log).

**Comment by topps** [comment]
Thanks sergey

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Aug 24, 2016 at 9:41 AM +0100, "Sergey Rud" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Catskan<https://github.com/Catskan>

I think we will figure out it faster if you are able to provide SSH access to your server and Database credentials. You may email me sergey.rud@itrexgroup.com<mailto:sergey.rud@itrexgroup.com> and I will try to install oLab on your server. Then I'll come back here with the reason of installation failure, which may be helpful for others.

If you don't able to do that, please clean Database, Apache and PHP log, then reinstall oLab (master branch) and send me DB, Apache and PHP log files (both access log and error log).

-

**Comment by Catskan** [comment]
Hi @sergey-rud 

My server has not a outside access with ssh :/.

I flush all my log files and reinstall with master branch oLab.

After install, I have ` Fatal error: Call to a member function uri() on null in /var/www/html/openlabyrinth/application/classes/kohana/exception.php on line 50`

![error olab](https://cloud.githubusercontent.com/assets/17289964/17961855/461ad0c8-6aae-11e6-9671-81dbfa1ebfd6.PNG)

I had a warning for PECL HTTP while the package is installed in my debian.
![openlaby-install](https://cloud.githubusercontent.com/assets/17289964/17961880/6030d75a-6aae-11e6-9e1d-650709f7b82d.PNG)

log apache : 
[apache2.zip](https://github.com/olab/Open-Labyrinth/files/436488/apache2.zip)

log MySql : 
[mysql.zip](https://github.com/olab/Open-Labyrinth/files/436489/mysql.zip)

**Comment by sergey-rud** [comment]
Seems this is the reason:
`[Thu Aug 25 06:03:34.267351 2016] [:error] [pid 12158] [client 134.59.53.4:17334] PHP Warning:  chmod(): Operation not permitted in /var/www/html/openlabyrinth/installation/classes/installation.php on line 151, referer: http://timide.unice.fr/openlabyrinth/installation/index.php`

Please make document root folder writable. Run `sudo chown -R apache:apache openlabyrinth/ && sudo chmod -R 0775 openlabyrinth/` **before** start the installation.

Please note that web server user can be ‘www-data’ instead of ‘apache’ or any other. It depends on your configuration, but typically it's ‘www-data’.


Also note that file structure for your case should be:
/var/www/html/openlabyrinth/database/...
/var/www/html/openlabyrinth/.gitignore
/var/www/html/openlabyrinth/www/installation/…
/var/www/html/openlabyrinth/www/...
Instead of
/var/www/html/openlabyrinth/installation/…
/var/www/html/openlabyrinth/…

This is not a reason of installation failure, but I don’t recommend to change repository structure due to future improvements.

**Comment by sergey-rud** [comment]
@Catskan , @madcat2000 Please check suggestions above and reopen the issue if the problem persists.

**Comment by Catskan** [comment]
Hi,

I tried your suggestions and I've again a error message, but different ...

Is it : 
`The requested URL /openlabyrinth/home/login was not found on this server.`

mod_rewrite is enable, but I haven't this home directory in openlabyrinth folder ...

**Comment by sergey-rud** [comment]
Hi,

did you try do: https://github.com/olab/Open-Labyrinth/wiki/After-installation-I-try-to-login-but-I-get-404-error ?

**Comment by Catskan** [comment]
Hi,

Oh thanks. my default.conf is ok but not activated. I actived this and Openlabyrinth works !

Thanks you very much Sergey :)

**Comment by sergey-rud** [comment]
You're welcome!
