### ISSUE TITLE
new release candidate

### ISSUE THREAD

**Issue by cyles** [olab/Open-Labyrinth#110]
Hi Sergey,
We've been running an older RC for some time and I'm interested in upgrading to the latest RC, but am very confused about the new Composer dependency.

The way I've been installing is to copy the contents of the www folder to my /var/www/html directory and sometimes /var/www/html/olab or other places.

When upgrading, I follow the process detailed in the wiki to overwrite most (but not all) of the /var/www/html directory with the new files.

Also note that I don't have shell access on my production server, so I don't have a command line to 'run things'.

Could you please provide some explicit and complete instructions for doing clean installs and upgrades of the new RC in the wiki pages?

Thanks,
Cyle

**Comment by sergey-rud** [comment]
Hi Cyle !
I updated next pages:
* [System requirements](https://github.com/olab/Open-Labyrinth/wiki/System-Requirements)
* [Installing Open Labyrinth](https://github.com/olab/Open-Labyrinth/wiki/Installing-Open-Labyrinth)
* [Updating Open Labyrinth](https://github.com/olab/Open-Labyrinth/wiki/Updating-Open-Labyrinth#upgrade-minor-versions)

Let me know if something still unclear.

If you don’t have SSH access you may do all of it on your local machine and then copy files **and DB** using FTP and/or web hosting control panel (eg. cPanel, etc).
