### ISSUE TITLE
installation - "No database selected"

### ISSUE THREAD

**Issue by tlareg** [olab/Open-Labyrinth#112]
Hi, 

I'm trying to install OL on **Win10 XAMPPv5.6.24.** When clicking "_Install and go to the login page_" (3rd step of installation wizard) message "No database selected" is displayed. I gave existing database name in previous step. (About half year ago I installed OL succesfully and had no problem with this).

> Apache/2.4.23
> PHP 5.6.24
> 10.1.16-MariaDB
> libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

Open-Labyrinth version - clone from master branch.

I think script stops at ```/www/installation/classes/installation.php``` method ```proceed``` line ```Installation::populateDatabase(INST_DOCROOT.'sql/CreateDB.sql');```

Thank you in advance

**Comment by sergey-rud** [comment]
Hi @tlareg !

I have exactly the same environment on my home computer and it works well.

Could you attach screenshot with the error and also attach error logs?
Does http://localhost/phpmyadmin/ work well?

Some thoughts:
- run XAMPP as administrator
- change Host Name from “localhost” to “127.0.0.1” (I didn’t do this)
- check DB user’s login, password and privileges (I use the default user “root” without password).

**Comment by tlareg** [comment]
In field DB user I typed "admin" instead of "root" which is my default user too.
Now with user "root" everything works fine. 

Maybe checking if given DB user name is real name of existing mysql user and displaying appropriate error message will help someone in the future.

Thanks!
