### ISSUE TITLE
Error re-auth after logout

### ISSUE THREAD

**Issue by Catskan** [olab/Open-Labyrinth#114]
HI,

I just see a error in my openlabyrinth configuration. When I logout a user for login an other, on the next login, I have the error : 
`Whoops! Looks like something got lost in the Labyrinth.
A message has been sent to the technical team. They will look into this issue.` but nothing append in my apache log.

I see in the url, I have `http://myserver.domain.com/openlabyrinth/openlabyrinht` but I can't find the config file to correct this.

My php.log 
```
ERROR: HTTP_Exception_404 [ 404 ]: The requested URL openlabyrinht was not found on this server. ~ SYSPATH/classes/kohana/request/client/internal.php [ 87 ]
2016-11-29 05:08:06 --- ERROR: type: HTTP_Exception_404; code: 404; message: The requested URL openlabyrinht was not found on this server.; file: /var/www/html/openlabyrinth/system/classes/kohana/request/client/internal.php; line: 87; browser: -; browser version: -; resolution: 1920x1080; user: admin

```

How can I find this file ?

Thanks you in advance.

Catskan

**Comment by sergey-rud** [comment]
Hi,
You can find configuration file in Open-Labyrinth\www\config.json

**Comment by Catskan** [comment]
Thanks you very much, it's ok :).
