### ISSUE TITLE
Not recording responses

### ISSUE THREAD

**Issue by ezgopi** [olab/Open-Labyrinth#90]
Hi,

I am using OpenLabyrinth v3.3, and created a labyrinth. The nodes have several questions and responses that the user has to enter.
However when I enter the information (pick/ multiple choice)and go on to "End session and feedback" all the questions are showing "no response". The application is not capturing the response recorded during the session.

![openlab-problem](https://cloud.githubusercontent.com/assets/1928030/5746286/7d474aac-9c26-11e4-9e28-8596fbc9182d.jpg)

Not sure what is the problem. I did try re-installing several times.

**Comment by topps** [comment]
That might be a wee bug that arose sometime around v3.3 – can you send me a copy of your case as an Export file (Advanced format)? I will load it onto our demo server (running 3.3.1) and see if it works there or what else might be wrong.

Also if you send me a bit of info about yourself, I can set you up with a test account on the demo server so you can see the case there for yourself.

David Topps
Topps AT ucalgary DOT ca

**Comment by ezgopi** [comment]
Hi,
I installed the v3.3.1 and its recording responses now.

Thanks
Gopi
