### ISSUE TITLE
Upgrading Openlabyrinth questions?

### ISSUE THREAD

**Issue by sgul-labyrinth** [olab/Open-Labyrinth#91]
Centos 6
I am trying to upgrade OpenLabyrinth to V3,3 under Centos. I have copied over the files/folders as per the instructions at the bottom of this doc (update manually section):
https://github.com/olab/Open-Labyrinth/wiki/Updating-Open-Labyrinth
When I use the updatedatabase URL the webpage hangs. Where does this URL look in order to upgrade the database? Are there any other instructions for a manual upgrade to 3.3?
Thanks
Paul

**Comment by joekoral** [comment]
What this question ever answered? I am having the same issue.

**Comment by sergey-rud** [comment]
Please see the issue #113
