### ISSUE TITLE
MySQL password contains $ sign - 404 ERROR after installation

### ISSUE THREAD

**Issue by bisho26** [olab/Open-Labyrinth#92]
A $ sign in the password for the MySQL user enables a successful installation, but produces a 404 ERROR after installation. 

Issue resolved after changing password to one without a $ sign

**Comment by topps** [comment]
Thanks for you help in debugging this. Much appreciated.

David Topps
Professor, Family Medicine
OpenLabyrinth Development Consortium Lead
