### ISSUE TITLE
Advanced Export Does Not Work

### ISSUE THREAD

**Issue by number-sense** [olab/Open-Labyrinth#94]
Hi,

 I installed the new version of Open-Labyrinth (3.3.1). I have two issues hoping you can help me with. 

1. I created a new labyrinth, I can export it only using the Medbiquitous VP feature. I tried the Advanced Export feature, but when I click export it displays the following error message:

"Whoops! Looks like something got lost in the Labyrinth.
A message has been sent to the technical team. They will look into this issue.
Please use the "back" arrow on your web browser to return to where you were before this happened."

2. Can you please tell me how can I export the labyrinth files in a way that can be browsed/viewed by other users who only have a web browser, namely they do not have the Open Layrinth tool? 

Thanks in Advance

**Comment by a-zharkov** [comment]
Hi @number-sense ,
Thank you for you report. We will look into the issue in the "Advanced Export" functionality.
To share the labyrinth to the other users you don't need to export it. You need to set the Security of the labyrinth to "Open" in labyrinth details page and this labyrinth will appear on the main page, you can copy the link and send it to another user.

If you go to http://demo.openlabyrinth.ca/ you will see the list of the "Open" labyrinths and you can play any of them. For example, this one: http://demo.openlabyrinth.ca/renderLabyrinth/index/5

I think that David (@topps) can provide you more detailed instructions, but you can also check the latest OpenLabyrinth User Guide - http://demo.openlabyrinth.ca/documents/UserGuide.pdf

Please let me know if you have any questions.

**Comment by number-sense** [comment]
Thanks for your explanation, however, I want to use the open labyrinth only as a tool to generate labyrinth use cases, which will be viewed by others privately as part of another website after they log in there!

**Comment by AlonaZSMU** [comment]
Hello, I'm using OpenLabyrinth , and have a need to export a case in doc format. Hw can I do it?
Many Thanks
Alona

**Comment by topps** [comment]
Do you need to export the case content or the session reports?


Prof David Topps
OpenLabyrinth Development Consortium Lead
