### ISSUE TITLE
User limitation of 12 users, possible to overcome?

### ISSUE THREAD

**Issue by a-zharkov** [olab/Open-Labyrinth#97]
I received email from andrey.popov85@gmail.com

> Hi,
> I have faced a problem when working with OpenLabyrinth software. The thing is we can only add 12 users in the database, no more.
> I would like to enquire if it is possible to increase the limit in the number of users to register with OpenLabyrinth? If so, would it be possible for you to provide some instructions?

> Thank you for your response in advance,
> Andrii P.

On the demo server we have a lot of users more that 12. There is no limitation on the users.
Could you please provide screen shots. Thank you.

**Comment by Popov85** [comment]
Hi, again!
Seemingly, we couldn't add users with e-mail address that had already existed in the database.
Now, adding new users with unique e-mails is working.
Probably, it would be correct to reveal the reason why a new user cannot be added after every failed attempt to register. The current version of OpenLabyrinth 3.3.sq does not provide any warning.
Thank you for your reply!

**Comment by a-zharkov** [comment]
@Popov85 Thank you for your clarification. Yes, it will be more correctly to display the warning message.
Will be fixed in next release.

**Comment by sergey-rud** [comment]
Fixed.
