### ISSUE TITLE
Forum error when ONLY_FULL_GROUP_BY set for MySQL

### ISSUE THREAD

**Issue by Thoughtfulmonkey** [olab/Open-Labyrinth#99]
After installation, clicking on the link to the forums lead to the 404 error page.

The issue was traced to application/classes/model/leap/dforum.php

In the getAllForums method there is a query that fails if the sql_mode variable of ONLY_FULL_GROUP_BY is set.  I didn't even know it was on, so I've just turned it off, but the MySQL reference indicates this is on by default since 5.7.5, and so might cause problems in future.

**Comment by topps** [comment]
Ah, good tip. Thank you. I will fwd this to the dev team

Sent from my Android phone using TouchDown (www.nitrodesk.com)

-----Original Message-----

**Comment by sergey-rud** [comment]
Hi @Thoughtfulmonkey, thank you for your report.

I have fixed this bug in the release-candidate branch. If Open-Labyrinth is already installed (I assume release-candidate branch), you will need to update Open-Labyrinth as usual **and** apply this fix manually by adding the following line `"variables"     => ['sql_mode' => 'NO_ENGINE_SUBSTITUTION']` to the www/application/config/database.php

So the file should look like:
```
<?php
/**
 * Open Labyrinth [ http://www.openlabyrinth.ca ]
 *
 * Open Labyrinth is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Open Labyrinth is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open Labyrinth.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright Copyright 2012 Open Labyrinth. All Rights Reserved.
 *
 */
defined('SYSPATH') or die('No direct access allowed.');

$config = array();
        $config["default"] = array(
            "type"          => "mysql",
            "driver"        => "standard",
            "connection"    => array(
                "persistent"    => FALSE,
                "hostname"      => "localhost",
                "port"          => "",
                "database"      => "olab",
                "username"      => "root",
                "password"      => "",
                "variables"     => ['sql_mode' => 'NO_ENGINE_SUBSTITUTION'], // NEW LINE
            ),
            "caching"       => FALSE,
            "charset"       => "utf8",
            "profiling"     => FALSE,
            "table_prefix"  => "",
        );

        return $config;
```
